### ISSUE TITLE
until restart server a new value will reflect

### ISSUE THREAD

**Issue by hoasung01** [refinery/refinerycms-settings#39]
I have an issue when update a refinery settings value in admin page and it only reflects until restart server

      class AdminMailer < ApplicationMailer

      default to: "#{Refinery::Setting.find_or_set(:admin_email, "xyz@abc.com", scoping: "mailer")}", from: "abc@abc.com"

      def notify_to_admin(email, saving_up_information)
        # code here
      end
    end

my admin_email from default to always get old value so is there a way to take effect this change without restart server?

**Comment by bricesanchez** [comment]
@hoasung01 Did you found a solution?

**Comment by bricesanchez** [comment]
Closed due to inactivity.
