### ISSUE TITLE
The action 'index' could not be found for Refinery::Blog::Admin::SettingsController

### ISSUE THREAD

**Issue by usmanidrees1234** [refinery/refinerycms-settings#49]
Index action missing in Refinery::Blog::Admin::SettingsController

getting this:
AbstractController::ActionNotFound (The action 'index' could not be found for Refinery::Blog::Admin::SettingsController):

**Comment by anitagraham** [comment]
I think this is an issue within Refinery::Blog, not settings. 
Blog has its own controller for Settings.
